### ISSUE TITLE
Docs is wrong & Missing release tag

### ISSUE THREAD

**Issue by razbensimon** [jsmith/changes-since-last-tag#11]
Hello, 
I start using your GitHub action.
I Had some issues with it, and by debugging I found some of the problems.

- the docs are wrong 
  - `v1` tag is not exists 
  - `any_changes` should be `any_changed`
- from some reason, `0.3.2` doesn't work. And that is actually the version that GitHub's **market** tells to install.
  - but `uses: jsmith/changes-since-last-tag@main` works. Can you release a new tag?

Feature request:
- support `minimatch` options object. (e.g `{ dot: true }`)

Thanks for your time!

**Comment by jsmith** [comment]
Thanks for letting me know about these issues! Let me take a look later today.

**Comment by jsmith** [comment]
Ok I've fixed the docs and quickly looked at adding the minimatch options! It doesn't look like too much work (you just have to pass the options through to minimatch) but I don't have too much free time right now so I will look at adding the options in a few weeks.

**Comment by razbensimon** [comment]
Thanks!

**Comment by jsmith** [comment]
Ok just released `v0.4.0` with minimatch options :)
